import type { Metadata } from 'next';
import Link from 'next/link';
import { SiteHeader } from '@/components/SiteHeader';
import { COLUMN_SOURCES } from '@/lib/sourceManifest';

export const metadata: Metadata = {
  title: 'Certification Systems — Urevangelium',
  description: 'Public diagrams of the source, verification, alignment, English, and release rules governing every Urevangelium tradition column.',
};

const outcome = {
  'source-verified': 'Eligible source-derived cells are published; exceptions remain explicit.',
  provisional: 'Evidence is published with provisional status until its remaining checks pass.',
  'requires-rebuild': 'The current display is held for reconstruction from the named governing source.',
};

export default function CertificationSystemsPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <SiteHeader />
      <div className="border-b border-rule-hairline bg-bg-elevated px-4 py-2 text-sm text-ink-muted">
        <Link href="/matthew/1/1" className="hover:text-ink-primary">← Back to the Gospel table</Link>
        <span className="mx-2">/</span><span className="font-medium text-ink-primary">Certification systems</span>
      </div>
      <main className="mx-auto w-full max-w-7xl flex-1 px-6 py-10">
        <header className="max-w-4xl border-b border-rule-strong pb-8">
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-accent-gold">Public methodology</p>
          <h1 className="mt-2 text-4xl font-semibold tracking-tight text-ink-primary">How each tradition is certified</h1>
          <p className="mt-4 text-lg leading-relaxed text-ink-secondary">Each column preserves a different historical object. The common framework below checks evidence without allowing an alignment text, dictionary, or neighboring tradition to replace that object.</p>
          <div className="mt-5 rounded border-l-4 border-accent-gold bg-bg-elevated px-5 py-4 text-sm text-ink-secondary"><strong className="text-accent-gold">Orange English</strong> is generated by Urevangelium’s documented system. Normal English is directly admitted through the column’s certified source chain. Orange never means that the English appears in the manuscript.</div>
        </header>

        <section className="mt-10 space-y-10" aria-label="Column certification diagrams">
          {COLUMN_SOURCES.map((column) => {
            const text = column.sources.filter((source) => source.role === 'text');
            const checks = column.sources.filter((source) => source.role === 'verification');
            const aids = column.sources.filter((source) => source.role === 'alignment' || source.role === 'gloss');
            const stage = (title: string, body: React.ReactNode) => <div className="min-w-0 flex-1 rounded border border-rule-hairline bg-bg-page p-4"><h3 className="text-xs font-semibold uppercase tracking-wider text-ink-muted">{title}</h3><div className="mt-2 text-sm leading-relaxed text-ink-secondary">{body}</div></div>;
            const names = (sources: typeof column.sources) => sources.length ? <ul className="list-disc space-y-1 pl-4">{sources.map((source) => <li key={source.name}>{source.name}</li>)}</ul> : <span className="italic text-ink-muted">Not yet registered</span>;
            return (
              <article id={column.id} key={column.id} className="scroll-mt-24 overflow-hidden rounded-lg border border-rule-strong bg-bg-elevated">
                <div className="border-b border-rule-hairline px-5 py-4"><p className="text-xs uppercase tracking-wider text-ink-muted">Position {column.position} · {column.tradition}</p><h2 className="mt-1 text-2xl font-semibold text-ink-primary">{column.label}</h2><p className="mt-1 text-sm text-ink-secondary">{column.displayedObject}</p></div>
                <div className="flex flex-col gap-2 p-5 lg:flex-row lg:items-stretch">
                  {stage('1 · Governing text', names(text))}<div className="self-center text-accent-gold">→</div>
                  {stage('2 · Independent checks', names(checks))}<div className="self-center text-accent-gold">→</div>
                  {stage('3 · Placement and English', names(aids))}<div className="self-center text-accent-gold">→</div>
                  {stage('4 · Rule gate', <><p>{column.rules[0]}</p><p className="mt-2"><strong>Never:</strong> {column.prohibited[0]}.</p></>)}<div className="self-center text-accent-gold">→</div>
                  {stage('5 · Public result', <><p>{outcome[column.status]}</p><p className="mt-2 font-medium text-ink-primary">Current status: {column.status}</p></>)}
                </div>
                <div className="border-t border-rule-hairline px-5 py-4 text-sm text-ink-secondary"><strong className="text-ink-primary">Exception rule:</strong> when independent evidence does not converge, the system labels the result provisional or withholds it. It does not resolve disagreement by majority vote across dependent sources, and English meaning never crosses from another tradition column.</div>
              </article>
            );
          })}
        </section>
      </main>
    </div>
  );
}
