// Beth Mardutho / SBL standard consonantal transliteration for Syriac.
// Vowel points are not present in the Peshitta source, so this is a
// consonant-only fallback — used only when no phonetics entry exists.

const CONSONANTS: Record<string, string> = {
  'ܐ': 'ʾ',
  'ܒ': 'b',
  'ܓ': 'g',
  'ܕ': 'd',
  'ܗ': 'h',
  'ܘ': 'w',
  'ܙ': 'z',
  'ܚ': 'ḥ',
  'ܛ': 'ṭ',
  'ܝ': 'y',
  'ܟ': 'k',
  'ܠ': 'l',
  'ܡ': 'm',
  'ܢ': 'n',
  'ܣ': 's',
  'ܤ': 's',
  'ܥ': 'ʿ',
  'ܦ': 'p',
  'ܨ': 'ṣ',
  'ܩ': 'q',
  'ܪ': 'r',
  'ܫ': 'š',
  'ܬ': 't',
  'ܖ': 'r',
  'ܜ': 'ṭ',
  'ܞ': 's',
};

function consonantsOnly(text: string): string {
  if (!text) return '';
  const parts: string[] = [];
  for (const ch of text) {
    const cp = ch.codePointAt(0)!;
    if (cp >= 0x0730 && cp <= 0x074A) continue; // skip diacritics / vowel marks
    const mapped = CONSONANTS[ch];
    if (mapped !== undefined) parts.push(mapped);
  }
  return parts.join('');
}

// ── Phonetics cache ───────────────────────────────────────────────────────────
// Generated by scripts/generateSyriacPhonetics.ts — maps Syriac tokens to
// their Western Syriac phonetic transliteration (macrons for long vowels).

let _phonetics: Record<string, string | null> | null = null;

function loadPhonetics(): Record<string, string | null> {
  if (_phonetics) return _phonetics;
  try {
    // Dynamic require so the JSON is loaded at runtime server-side without
    // bundling 8K entries into every client chunk.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    _phonetics = require('@/data/sources/peshitta/phonetics.json') as Record<string, string | null>;
  } catch {
    _phonetics = {};
  }
  return _phonetics;
}

// ── Public API ────────────────────────────────────────────────────────────────

export function transliterateSyriac(text: string): string {
  if (!text) return '';
  const phonetics = loadPhonetics();
  const cached = phonetics[text];
  // Explicit null means "uncertain" — fall back to consonants rather than hiding the word.
  if (cached !== undefined && cached !== null) return cached;
  return consonantsOnly(text);
}
